function [methodinfo,structs,enuminfo,ThunkLibName]=mwtirem3libproto_win64
%MWTIREM3LIBPROTO_WIN64 Create structures to define interfaces found in 'tirem3'.

%This function was generated by loadlibrary.m parser version  on Wed Oct 18 18:32:50 2023
%perl options:'tirem3.i -outfile=mwtirem3libproto_win64.m -thunkfile=mwtirem3lib_thunk_pcwin64.c -header=tirem3.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'mwtirem3lib_thunk_pcwin64');
% void GetTiremNum ( char * version ); 
fcns.thunkname{fcnNum}='voidcstringThunk';fcns.name{fcnNum}='GetTiremNum'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'cstring'};fcnNum=fcnNum+1;
% void RunTiremAnal ( float tx_antenna_height , float rx_antenna_height , float frequency , int num_profile_points , const float * profile_elevation , const float * profile_distance , int extension , float refractivity , float conductivity , float permittivity , float humidity , const char * polarization , int num_rain_rates , const float * rain_rates , float rain_elevation , char * version , char * propagation_mode , float * fresnel_clearance , float * total_loss , float * free_space_loss , float * rain_loss , float * total_troposphere_loss , float * total_diffraction_loss , float * absorption_loss , float * troposcatter_angle , float * tx_horizon_angle , float * rx_horizon_angle , float * tx_troposcatter_angle , float * rx_troposcatter_angle , int * tx_horizon_index , int * rx_horizon_index , float * path_length , float * tx_path_length , float * rx_path_length , const char * activation_key ); 
fcns.thunkname{fcnNum}='voidfloatfloatfloatint32voidPtrvoidPtrint32floatfloatfloatfloatcstringint32voidPtrfloatcstringcstringvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrcstringThunk';fcns.name{fcnNum}='RunTiremAnal'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'single', 'single', 'single', 'int32', 'singlePtr', 'singlePtr', 'int32', 'single', 'single', 'single', 'single', 'cstring', 'int32', 'singlePtr', 'single', 'cstring', 'cstring', 'singlePtr', 'singlePtr', 'singlePtr', 'singlePtr', 'singlePtr', 'singlePtr', 'singlePtr', 'singlePtr', 'singlePtr', 'singlePtr', 'singlePtr', 'singlePtr', 'int32Ptr', 'int32Ptr', 'singlePtr', 'singlePtr', 'singlePtr', 'cstring'};fcnNum=fcnNum+1;
methodinfo=fcns;